apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          # Indica a Kubernetes usar la imagen local almacenada y no descargar de Docker Hub
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SERVER_PORT
              value: "9000"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
              # Desactiva el sistema de descubrimiento de servicio en SpringCloud completamente
              # Es una capa por encima de eureka
              # Cerramos la puerta de forma definitiva
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            # - name: MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT
            #   value: "http://lgtm:4318/v1/traces"
            # - name: MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT
            #   value: "http://lgtm:4318/v1/logs"
            # - name: MANAGEMENT_OTLP_METRICS_EXPORT_URL
            #   value: "http://lgtm:4318/v1/metrics"
            # - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
            #   value: "1.0"
              # Le estamos diciendo a Spring Boot dónde validar el JSON WEB TOKEN
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/ecommerce-realm"