spring:
  threads:
    virtual:
      enabled: true
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: aa1032f4896968
    password: 1930fd4ce0fbef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms # Primera espera de 3 segundos
          max-attempts: 3          # Máximo 3 intentos totales
          max-interval: 10000ms   # No esperar más de 10 segundos
          multiplier: 2.0         # Backoff exponencial (3s, 6s, 10s)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

logging:
  level:
    root: INFO
    com.ecommerce: INFO
