spring:
  cloud:
    config:
    # Desactiva el descubrimiento de Spring Cloud completamente
      enabled: false
    discovery:
      enabled: false
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/v1/product/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/v1/order/**
        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/api/v1/inventory/**
  rabbitmq:
    host: rabbitmq

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://keycloak:8080/realms/ecommerce-realm